---
services:
  web:
    container_name: xcrypto
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
  postgres-db:
    container_name: postgres-db
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'PG123456'
    volumes:
      - "./data/postgresql/data:/var/lib/postgresql/data"
      - "./data/postgresql/log:/var/log/postgresql"
      # - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "5432:5432"
  redis-db:
    container_name: redis-db
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
...

